apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=         # base64("rootpass")
  MYSQL_PASSWORD: dG9kb19wYXNz              # base64("todo_pass")