apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # headless service for simplicity (optional)