apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
  labels:
    app: todo-app
spec:
  containers:
    - name: todo-app
      image: vanamalamanish26/todo-app:latest
      ports:
        - containerPort: 8080